# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# action 이름
name: deploy

# action 트리거 조건 (해당 브랜치에 푸쉬될 때. 콤마 표시를 넣어서 복수의 브랜치를 설정할 수 있다)
on:
  push:
    branches: [main]

# action 동작
jobs:
  # OS 환경
  build:
    runs-on: ubuntu-16.04

    # Nodejs 런타임 정보 설정
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
